### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by vanhauser-thc** [AAArdu/hastefuzz#1]
Hi!
on which specific afl++ commit is this variant based on?
and can you please provide some insights what your idea behind this variant is?
thank you :)

**Comment by AAArdu** [comment]
Hi, @vanhauser-thc
This idea is still in development, we think it needs further improvements and experiments. If possible, we are honored to help integrate this idea into AFL++ in the future.

The variant is based on afl++ commit 33eba1fc5652060e8d877b02135fce2325813d0c .
The basic idea is: using some metrics to filter out valuable inputs (e.g. that need further sanitizer check for bugs), currently we use the uniqueness of path trace (the hash ID of the coverage bitmap) as the metric. For bug detection with ASAN, we compile two versions of binary, one with sanitizer and the other without. We know that the binary without sanitizer is faster, and during fuzzing, we use binary without sanitizer to get bitmap, and only the hash ID is unique, we execute the input on binary with sanitizer. For coverage only, the inputs with unique hash ID need further processing (the bitmap comparison for new coverage). Note that the hash ID is already calculated in mode like afl++ fast mode, which is the default mode of afl++, we can reuse it without recalculation.  In this way, we hope to improve the throughput of fuzzing.

**Comment by AAArdu** [comment]
Btw, for bug detection, the bitmap hash ID metric is not 100% correct in theory. However, our experience and some limited experiments show that it is a reasonable metric for real-world programs: Two identical path traces express the same bug-existing status. And we found during fuzzing, lots of generated inputs execute the same path (with the same bitmap hast ID),   
especially for the later period of fuzzing, that's why we think there is space to improve throughput.

**Comment by vanhauser-thc** [comment]
I looked at the changes you made and they are not a lot, so future integration would be easy.
I am still not sure I understand what you are doing and why, but looking forward to your paper :-) if you have something you can/want to send to me, email to mh(at)mh-sec(dot)de
